### ISSUE TITLE
Uhm, what's the difference?

### ISSUE THREAD

**Issue by dmlb2000** [skorhone/wsl2-custom-network#1]
So I found an existing HCN powershell module... https://www.powershellgallery.com/packages/HNS/0.2.4

What's the difference?

**Comment by skorhone** [comment]
Not much, I just stripped the parts that weren't required. This way the script is far easier to audit in an environment where you can't pull random stuff on your workstation.

There's a reference to original library at the top of readme.md. Considering this is such a small repo, didn't feel necessary to add another reference in the hns PowerShell file.
